GET http://localhost:8080/veterinario/10

########

GET http://localhost:8080/establecimiento

###############################

POST http://localhost:8080/establecimiento
Content-Type:  application/json
Accept: application/json

{
  "nombre": "cat Happy",
  "ciudad":"La Paz",
  "direccion":"Villa San Antonio",
  "telefono":"4526782",
  "email": "cat@gmail.com",
  "horaAtencion":"Lunes a Viernes 9:00 - 20:00"
}